apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: '{{ include "app.name" . }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: '{{ include "app.name" . }}'
