apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lookerfiles
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage.models }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: looker-db
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage.database }}
